# Generated by Django 4.2.2 on 2023-06-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['id'],
                'unique_together': {('skill',)},
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('job', models.CharField(max_length=50, verbose_name='Position')),
                ('apart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.apartmodel')),
                ('skill', models.ManyToManyField(to='personal.skillsmodels')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
