# Generated by Django 4.2.2 on 2023-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_employeemodel_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
