# Generated by Django 4.2.2 on 2023-06-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_employeemodel_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
