# Generated by Django 4.2.2 on 2023-06-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_employeemodel_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
    ]
