# Generated by Django 4.2.2 on 2023-06-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmodel',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmodel',
            name='short_name',
            field=models.CharField(default=1, max_length=50, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='apartmodel',
            unique_together={('name', 'short_name')},
        ),
    ]
