# Generated by Django 4.2.2 on 2023-06-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_apartmodel_name_apartmodel_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmodel',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='Abbreviation'),
        ),
    ]
