# Generated by Django 4.2.2 on 2023-06-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_alter_apartmodel_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='people', verbose_name='Avatar'),
        ),
    ]
