# Generated by Django 4.2.2 on 2023-06-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0004_apartmodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmodel',
            name='img',
        ),
    ]
